"""
app.py

Visual Tracking and Analysis System

Interactive Streamlit dashboard for Project 06 of the
SAM3 Learning Journey.

The dashboard uses the reports already generated by the project and provides:

- Project overview
- Verified processing metrics
- Tracker history
- Trajectory analysis
- Confidence analysis
- Movement analysis
- Visual analytics
- Performance summary
- Results explorer
- Exportable report access

Run with:

    streamlit run app.py
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import streamlit as st


# ============================================================
# PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parent

REPORTS_DIR = PROJECT_ROOT / "reports"
DOCS_DIR = PROJECT_ROOT / "docs"

TRACKER_SUMMARY = REPORTS_DIR / "tracker_summary.csv"
TRAJECTORY_SUMMARY = REPORTS_DIR / "trajectory_summary.csv"
PERFORMANCE_SUMMARY = REPORTS_DIR / "performance_summary.csv"

TRAJECTORY_VISUALIZATION = REPORTS_DIR / "trajectory_visualization.png"
TRACKER_DURATION_CHART = REPORTS_DIR / "tracker_duration_chart.png"
CLASS_OBSERVATION_CHART = REPORTS_DIR / "class_observation_chart.png"
MOVEMENT_DISTANCE_CHART = REPORTS_DIR / "movement_distance_chart.png"
CONFIDENCE_CHART = REPORTS_DIR / "confidence_chart.png"
PERFORMANCE_CHART = REPORTS_DIR / "performance_chart.png"

RESULTS_DOC = DOCS_DIR / "RESULTS.md"
LIMITATIONS_DOC = DOCS_DIR / "LIMITATIONS.md"


# ============================================================
# STREAMLIT CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Visual Tracking and Analysis System",
    page_icon="🎯",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ============================================================
# DATA LOADING
# ============================================================

@st.cache_data
def load_csv(path: Path) -> pd.DataFrame:
    """
    Load a CSV report.
    """

    if not path.exists():
        return pd.DataFrame()

    return pd.read_csv(path)


@st.cache_data
def load_markdown(path: Path) -> str:
    """
    Load a Markdown documentation file.
    """

    if not path.exists():
        return ""

    return path.read_text(
        encoding="utf-8"
    )


tracker_df = load_csv(
    TRACKER_SUMMARY
)

trajectory_df = load_csv(
    TRAJECTORY_SUMMARY
)

performance_df = load_csv(
    PERFORMANCE_SUMMARY
)


# ============================================================
# HELPERS
# ============================================================

def metric_value(
    metric_name: str,
    default: str = "N/A",
) -> str:
    """
    Retrieve a metric from performance_summary.csv.
    """

    if performance_df.empty:
        return default

    if "metric" not in performance_df.columns:
        return default

    if "value" not in performance_df.columns:
        return default

    match = performance_df[
        performance_df["metric"] == metric_name
    ]

    if match.empty:
        return default

    return str(
        match.iloc[0]["value"]
    )


def show_image(
    image_path: Path,
    caption: str,
) -> None:
    """
    Display a report image if it exists.
    """

    if image_path.exists():

        st.image(
            str(image_path),
            caption=caption,
            use_container_width=True,
        )

    else:

        st.warning(
            f"Missing visualization: {image_path.name}"
        )


def download_csv_button(
    label: str,
    dataframe: pd.DataFrame,
    filename: str,
    key: str,
) -> None:
    """
    Create a CSV download button.
    """

    if dataframe.empty:
        return

    csv_data = dataframe.to_csv(
        index=False
    ).encode("utf-8")

    st.download_button(
        label=label,
        data=csv_data,
        file_name=filename,
        mime="text/csv",
        key=key,
    )


# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.title(
    "Project 06"
)

st.sidebar.markdown(
    "**Visual Tracking and Analysis System**"
)

st.sidebar.markdown("---")

page = st.sidebar.radio(
    "Navigation",
    [
        "Overview",
        "Tracker Explorer",
        "Trajectory Analysis",
        "Visual Analytics",
        "Performance",
        "Results",
        "Limitations",
    ],
)

st.sidebar.markdown("---")

st.sidebar.caption(
    "SAM3 Learning Journey"
)

st.sidebar.caption(
    "YOLO + ByteTrack + SAM 3"
)


# ============================================================
# HEADER
# ============================================================

st.title(
    "Visual Tracking and Analysis System"
)

st.caption(
    "YOLO object detection · ByteTrack tracking · "
    "SAM 3 segmentation · analytics · reporting"
)


# ============================================================
# OVERVIEW PAGE
# ============================================================

if page == "Overview":

    st.header(
        "Project Overview"
    )

    st.markdown(
        """
This dashboard provides an interactive interface for exploring the
results generated by **Project 06 — Visual Tracking and Analysis System**.

The project combines:

- YOLO object detection
- ByteTrack multi-object tracking
- Persistent tracker identities
- SAM 3 segmentation
- H.264 recorded-video output
- SQLite persistence architecture
- Tracker analytics
- Trajectory analysis
- Confidence analysis
- Movement analysis
- Performance reporting
"""
    )

    st.subheader(
        "Verified Processing Run"
    )

    col1, col2, col3 = st.columns(3)

    with col1:

        st.metric(
            "Processed Frames",
            metric_value(
                "Total Processed Frames",
                "75",
            ),
        )

    with col2:

        st.metric(
            "Observations",
            metric_value(
                "Total Observations",
                "246",
            ),
        )

    with col3:

        st.metric(
            "Unique Tracker IDs",
            metric_value(
                "Unique Tracker IDs",
                "6",
            ),
        )

    col4, col5, col6 = st.columns(3)

    with col4:

        st.metric(
            "Average Confidence",
            metric_value(
                "Average Confidence",
                "0.6815",
            ),
        )

    with col5:

        st.metric(
            "Average Tracker Duration",
            (
                metric_value(
                    "Average Tracker Duration (seconds)",
                    "2.7333",
                )
                + " s"
            ),
        )

    with col6:

        st.metric(
            "Total Movement",
            (
                metric_value(
                    "Total Movement Distance (pixels)",
                    "693.18",
                )
                + " px"
            ),
        )

    st.subheader(
        "System Pipeline"
    )

    st.code(
        """
Input Image / Video
        ↓
YOLO Object Detection
        ↓
ByteTrack Tracking
        ↓
Persistent Tracker IDs
        ↓
SAM 3 Segmentation
        ↓
Annotated H.264 Video
        ↓
Tracking Observations
        ↓
SQLite Persistence
        ↓
Tracker Analytics
        ↓
Trajectory Analytics
        ↓
Performance Analysis
        ↓
Reports + Dashboard
""",
        language="text",
    )

    st.subheader(
        "Verified Output"
    )

    st.code(
        "sam3_tracking_output_01.mp4",
        language="text",
    )

    st.info(
        "The current verified run contains "
        "75 processed frames, 246 observations, "
        "and 6 unique tracker IDs."
    )


# ============================================================
# TRACKER EXPLORER
# ============================================================

elif page == "Tracker Explorer":

    st.header(
        "Tracker Explorer"
    )

    if tracker_df.empty:

        st.error(
            "tracker_summary.csv could not be loaded."
        )

    else:

        tracker_ids = sorted(
            tracker_df["tracker_id"]
            .dropna()
            .unique()
            .tolist()
        )

        selected_tracker = st.selectbox(
            "Select Tracker ID",
            tracker_ids,
        )

        selected = tracker_df[
            tracker_df["tracker_id"]
            == selected_tracker
        ].iloc[0]

        st.subheader(
            f"Tracker {selected_tracker}"
        )

        col1, col2, col3 = st.columns(3)

        with col1:

            st.metric(
                "Class",
                selected["class_name"],
            )

        with col2:

            st.metric(
                "Observations",
                int(
                    selected["observations"]
                ),
            )

        with col3:

            st.metric(
                "Average Confidence",
                f"{selected['average_confidence']:.4f}",
            )

        col4, col5, col6 = st.columns(3)

        with col4:

            st.metric(
                "First Frame",
                int(
                    selected["first_frame"]
                ),
            )

        with col5:

            st.metric(
                "Last Frame",
                int(
                    selected["last_frame"]
                ),
            )

        with col6:

            st.metric(
                "Duration",
                f"{selected['duration_seconds']:.2f} s",
            )

        st.subheader(
            "All Tracker Records"
        )

        st.dataframe(
            tracker_df,
            use_container_width=True,
            hide_index=True,
        )

        download_csv_button(
            "Download Tracker Summary",
            tracker_df,
            "tracker_summary.csv",
            "download_tracker_summary",
        )

        st.subheader(
            "Tracker Duration"
        )

        show_image(
            TRACKER_DURATION_CHART,
            "Tracker Duration Chart",
        )

        st.subheader(
            "Detection Confidence"
        )

        show_image(
            CONFIDENCE_CHART,
            "Confidence Chart",
        )


# ============================================================
# TRAJECTORY ANALYSIS
# ============================================================

elif page == "Trajectory Analysis":

    st.header(
        "Trajectory Analysis"
    )

    if trajectory_df.empty:

        st.error(
            "trajectory_summary.csv could not be loaded."
        )

    else:

        trajectory_ids = sorted(
            trajectory_df["tracker_id"]
            .dropna()
            .unique()
            .tolist()
        )

        selected_tracker = st.selectbox(
            "Select Tracker ID",
            trajectory_ids,
            key="trajectory_tracker",
        )

        selected = trajectory_df[
            trajectory_df["tracker_id"]
            == selected_tracker
        ].iloc[0]

        col1, col2, col3 = st.columns(3)

        with col1:

            st.metric(
                "Movement Distance",
                f"{selected['movement_distance_pixels']:.2f} px",
            )

        with col2:

            st.metric(
                "Average Movement",
                f"{selected['average_movement_pixels']:.2f} px",
            )

        with col3:

            st.metric(
                "Frames Observed",
                int(
                    selected["frames_observed"]
                ),
            )

        col4, col5, col6 = st.columns(3)

        with col4:

            st.metric(
                "First Frame",
                int(
                    selected["first_frame"]
                ),
            )

        with col5:

            st.metric(
                "Last Frame",
                int(
                    selected["last_frame"]
                ),
            )

        with col6:

            st.metric(
                "Duration",
                f"{selected['duration_seconds']:.2f} s",
            )

        st.subheader(
            "Trajectory Summary"
        )

        st.dataframe(
            trajectory_df,
            use_container_width=True,
            hide_index=True,
        )

        download_csv_button(
            "Download Trajectory Summary",
            trajectory_df,
            "trajectory_summary.csv",
            "download_trajectory_summary",
        )

        st.subheader(
            "Trajectory Visualization"
        )

        show_image(
            TRAJECTORY_VISUALIZATION,
            "Tracked Object Trajectories",
        )

        st.subheader(
            "Movement Distance"
        )

        show_image(
            MOVEMENT_DISTANCE_CHART,
            "Movement Distance by Tracker",
        )

        st.caption(
            "Movement values are measured in image-space pixels "
            "and do not represent physical-world distance."
        )


# ============================================================
# VISUAL ANALYTICS
# ============================================================

elif page == "Visual Analytics":

    st.header(
        "Visual Analytics"
    )

    st.markdown(
        """
The visual analytics layer transforms structured tracking
observations into charts that make tracker behavior easier to inspect.
"""
    )

    st.subheader(
        "Trajectory Visualization"
    )

    show_image(
        TRAJECTORY_VISUALIZATION,
        "Trajectory Visualization",
    )

    st.divider()

    st.subheader(
        "Tracker Duration"
    )

    show_image(
        TRACKER_DURATION_CHART,
        "Tracker Duration Chart",
    )

    st.divider()

    st.subheader(
        "Class Observations"
    )

    show_image(
        CLASS_OBSERVATION_CHART,
        "Class Observation Chart",
    )

    st.divider()

    st.subheader(
        "Movement Distance"
    )

    show_image(
        MOVEMENT_DISTANCE_CHART,
        "Movement Distance Chart",
    )

    st.divider()

    st.subheader(
        "Detection Confidence"
    )

    show_image(
        CONFIDENCE_CHART,
        "Confidence Chart",
    )

    st.divider()

    st.subheader(
        "Performance Summary"
    )

    show_image(
        PERFORMANCE_CHART,
        "Performance Chart",
    )


# ============================================================
# PERFORMANCE PAGE
# ============================================================

elif page == "Performance":

    st.header(
        "Performance Analysis"
    )

    if performance_df.empty:

        st.error(
            "performance_summary.csv could not be loaded."
        )

    else:

        col1, col2, col3 = st.columns(3)

        with col1:

            st.metric(
                "Frames",
                metric_value(
                    "Total Processed Frames",
                    "75",
                ),
            )

        with col2:

            st.metric(
                "Observations",
                metric_value(
                    "Total Observations",
                    "246",
                ),
            )

        with col3:

            st.metric(
                "Tracker IDs",
                metric_value(
                    "Unique Tracker IDs",
                    "6",
                ),
            )

        col4, col5, col6 = st.columns(3)

        with col4:

            st.metric(
                "Avg. Observations / Frame",
                metric_value(
                    "Average Observations per Frame",
                    "3.28",
                ),
            )

        with col5:

            st.metric(
                "Average Confidence",
                metric_value(
                    "Average Confidence",
                    "0.6815",
                ),
            )

        with col6:

            st.metric(
                "Total Movement",
                (
                    metric_value(
                        "Total Movement Distance (pixels)",
                        "693.18",
                    )
                    + " px"
                ),
            )

        st.subheader(
            "Complete Performance Summary"
        )

        st.dataframe(
            performance_df,
            use_container_width=True,
            hide_index=True,
        )

        download_csv_button(
            "Download Performance Summary",
            performance_df,
            "performance_summary.csv",
            "download_performance_summary",
        )

        st.subheader(
            "Performance Chart"
        )

        show_image(
            PERFORMANCE_CHART,
            "System Performance Summary",
        )

        st.subheader(
            "Processing-Time Metrics"
        )

        st.write(
            "Total processing time:",
            metric_value(
                "Total Processing Time (seconds)",
            ),
        )

        st.write(
            "Average processing time per frame:",
            metric_value(
                "Average Processing Time per Frame (seconds)",
            ),
        )

        st.write(
            "Effective processing FPS:",
            metric_value(
                "Effective Processing FPS",
            ),
        )

        st.info(
            "The original complete pipeline runtime was not "
            "recorded during the verified run. These metrics "
            "remain N/A rather than using invented values."
        )


# ============================================================
# RESULTS PAGE
# ============================================================

elif page == "Results":

    st.header(
        "Verified Project Results"
    )

    results_markdown = load_markdown(
        RESULTS_DOC
    )

    if results_markdown:

        st.markdown(
            results_markdown
        )

    else:

        st.warning(
            "docs/RESULTS.md could not be loaded."
        )


# ============================================================
# LIMITATIONS PAGE
# ============================================================

elif page == "Limitations":

    st.header(
        "System Limitations and Failure Cases"
    )

    limitations_markdown = load_markdown(
        LIMITATIONS_DOC
    )

    if limitations_markdown:

        st.markdown(
            limitations_markdown
        )

    else:

        st.warning(
            "docs/LIMITATIONS.md could not be loaded."
        )


# ============================================================
# FOOTER
# ============================================================

st.divider()

st.caption(
    "Project 06 — Visual Tracking and Analysis System"
)

st.caption(
    "SAM3 Learning Journey · Peyman Miyandashti"
)
