"""
database.py

Database module for the Visual Tracking and Analysis System.

This module provides SQLite storage for processing sessions and
computer vision observations generated by the analysis pipeline.
"""

import sqlite3
from pathlib import Path


class AnalysisDatabase:
    """
    SQLite database for storing processing sessions and observations.
    """

    def __init__(self, database_path="data/analysis.db"):
        self.database_path = Path(database_path)

        self.database_path.parent.mkdir(
            parents=True,
            exist_ok=True
        )

        self.connection = sqlite3.connect(
            self.database_path
        )

        self.create_tables()

    def create_tables(self):
        """
        Create the required database tables.
        """

        cursor = self.connection.cursor()

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS sessions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                source TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                notes TEXT
            )
            """
        )

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS observations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id INTEGER NOT NULL,
                frame_number INTEGER,
                timestamp REAL,
                tracker_id INTEGER,
                class_id INTEGER,
                class_name TEXT,
                confidence REAL,
                x1 REAL,
                y1 REAL,
                x2 REAL,
                y2 REAL,
                notes TEXT,
                FOREIGN KEY (session_id)
                    REFERENCES sessions(id)
            )
            """
        )

        self.connection.commit()

    def create_session(self, source, notes=None):
        """
        Create a new processing session.

        Returns
        -------
        int
            Database ID of the new session.
        """

        cursor = self.connection.cursor()

        cursor.execute(
            """
            INSERT INTO sessions (source, notes)
            VALUES (?, ?)
            """,
            (source, notes)
        )

        self.connection.commit()

        return cursor.lastrowid

    def add_observation(
        self,
        session_id,
        frame_number,
        timestamp,
        tracker_id,
        class_id,
        class_name,
        confidence,
        bounding_box,
        notes=None
    ):
        """
        Store one computer vision observation.
        """

        x1, y1, x2, y2 = bounding_box

        cursor = self.connection.cursor()

        cursor.execute(
            """
            INSERT INTO observations (
                session_id,
                frame_number,
                timestamp,
                tracker_id,
                class_id,
                class_name,
                confidence,
                x1,
                y1,
                x2,
                y2,
                notes
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                session_id,
                frame_number,
                timestamp,
                tracker_id,
                class_id,
                class_name,
                confidence,
                float(x1),
                float(y1),
                float(x2),
                float(y2),
                notes
            )
        )

        self.connection.commit()

    def close(self):
        """
        Close the database connection.
        """

        self.connection.close()
